spring.application.name=nutricode

# ===== BANCO OCI (COM WALLET) =====
spring.datasource.url=jdbc:oracle:thin:@admin_medium?TNS_ADMIN=C:/Users/PC/Downloads/NUTRICODE-QUALITY-SPRINT4/Wallet_ADMIN&oracle.net.ssl_server_dn_match=true
spring.datasource.username=ADMIN
spring.datasource.password=Nutricode123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===== HIKARI (POOL) =====
spring.datasource.hikari.maximum-pool-size=2

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== SERVER =====
server.port=8080
server.address=0.0.0.0